name: .NET Build

on:
  push:
    branches: master

  pull_request:

  workflow_dispatch:
  
jobs:        
  build:
    if: ${{ startsWith(github.ref, 'refs/tags/') == false }}
    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [self-hosted] #, ubuntu-latest, windows-latest]
            BuildConfiguration: [ Release ]
        max-parallel: 2
        
    steps:
   
    - uses: actions/checkout@v5.0.0
      with:
        fetch-depth: '0'
        
    - name: Restore dependencies
      run: dotnet restore
        
    - name: Build
      id: build
      run: |
        dotnet build --no-restore --configuration ${{ matrix.BuildConfiguration }}
